### ISSUE TITLE
The imported data does not bear any resemblence to that shown on the video at present.

### ISSUE THREAD

**Issue by alanwilliams2018** [saasacademy/saas-template-wp#1]
The one click data import data seem to be broken.
It does not result in anything like that which is shown on the video.

**Comment by Vivekananthan** [comment]
Hi @alanwilliams2018, 

I tested the downloads today on a clean install it worked fine. 

So can you please email me -> vive [at] danmartell.com with the following details:
1. Did you uploaded Divi parent theme present in the zip file and then the Divi Child theme present in the zip?
2. Can you please share your website url, so I can take a look?
3. Is your current active theme is Divi Child theme? 

Please let me know all the detail through email and I will look into it. 

Thanks and closing this as we continue to troubleshoot via email. Thanks
